### ISSUE TITLE
Leverage App Engine's static handlers for public/ directory

### ISSUE THREAD

**Issue by steren** [JustinBeckwith/visionator#3]
App Engine Standard allows you serve static files without having the requests reaching your application, read more at https://cloud.google.com/appengine/docs/standard/nodejs/serving-static-files

Note that serving those files via the static mechanism of Express.js in addition to App Engine's static handlers is recommend for local development and for better app portability.

**Comment by JustinBeckwith** [comment]
Pull requests accepted!
